//Exercise #1

When a Mule app starts, a connectivity test runs on components, such as the HTTP or FTP connector. These connectors need to be linked to an external server and, if the test fails, the default behavior is to trigger a warning message and continue with the deployment of the app, instead of blocking the deployment.

You can modify this behavior by setting a number of reconnection attempts:

1. Try after an initial failure
2. Force the deployment to fail when all connection attempts are not successful.


- Fail Deployment (`failsDeployment`): Forces the deployment to fail if the connection breaks and any configured reconnection attempts have been reached.
- Reconnect (`reconnect`): Limits the number of reconnection attempts and the interval at which you need to execute them. For example, you might set a count of 5 reconnection attempts at a `frequency` of every `4000` milliseconds (ms). Default attempts are set at 2 at a frequency of `2000ms`.
- Example showing a failure after 5 reconnection attempts are reached with no success:

[source,xml]
----
<http:request-config name="HTTP_Request_Config" doc:name="HTTP Request Config">
  <http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80" >
    <reconnection failsDeployment="true" >
      <reconnect frequency="4000" count="5" />
    </reconnection>
  </http:request-connection>
</http:request-config>
----

#### Additional options to run the app after reconnection fails:

* Reconnect Forever (reconnect-forever): Sets attempts to reconnect at a given interval, for example, every 4000 ms for as long as the app runs. Defaults are set to every 2000 ms. Because there is no limit on the number of retries, no value for count is specified.

* Example that does not set a limit on the number of reconnection attempts:

      [source,xml]
----
<http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80">
  <reconnection>
    <reconnect-forever frequency="4000" count=”5”/>
  </reconnection>
</http:request-connection>
----
You are all set! Feel free to contact us should you have additional questions.
